# Define a configuração para rodar com imagens do Docker Hub
version: '2'
services:
  rabbit:
    extends:
      file: compose/shared/common.yml
      service: rabbit
  discovery:
    extends:
      file: compose/shared/common.yml
      service: discovery
  gateway:
    extends:
      file: compose/shared/common.yml
      service: gateway
    depends_on:
     - discovery
  services:
    extends:
      file: compose/shared/common.yml
      service: services
    depends_on:
     - rabbit
     - discovery
  ui:
    extends:
      file: compose/shared/common.yml
      service: ui
    depends_on:
     - gateway
  userauthentication:
    extends:
      file: compose/shared/common.yml
      service: userauthentication
    depends_on:
     - discovery
  mongo:
    extends:
      file: compose/shared/common.yml
      service: mongo
  onlyoffice:
    extends:
      file: compose/shared/common.yml
      service: onlyoffice_ambassador
  documents:
    extends:
      file: compose/shared/common.yml
      service: documents
    links:
     - onlyoffice:docker # documents precisa acessar o onlyoffice pelo host docker para não dar erro de certificado
    depends_on:
     - mongo
     - discovery
     - onlyoffice
  autuacao:
    extends:
      file: compose/shared/common.yml
      service: autuacao
    depends_on:
     - rabbit
     - discovery
  distribuicao:
    extends:
      file: compose/shared/common.yml
      service: distribuicao
    depends_on:
     - rabbit
     - discovery
  peticionamento:
    extends:
      file: compose/shared/common.yml
      service: peticionamento
    depends_on:
     - rabbit
     - discovery
  recebimento:
    extends:
      file: compose/shared/common.yml
      service: recebimento
    depends_on:
     - rabbit
     - discovery