version: '2'
services:
  rabbit:
    image: rabbitmq:management
    ports:
     - "15672:15672"
  servicos:
    image: services
    ports:
     - "8081:8081"
  peticionamento:
    image: peticionamento
    ports:
     - "8090:8090"
  recebimento:
    image: recebimento
    ports:
     - "8091:8091"
  autuacao:
    image: autuacao
    ports:
     - "8092:8092"
  distribuicao:
    image: distribuicao
    ports:
     - "8093:8093"
