# Define a configuração padrão complementar dos serviços
# As variáveis utilizadas neste arquivo estão definidas no arquivo .env
version: '2'
services:
  rabbit:
    ports:
     - "5672:5672"
     - "15672:15672"
  discovery:
    image: stfdigital-plataforma-discovery
    ports:
     - "8761:8761"
     - "47961:${JAVA_DEBUG_PORT}"
    environment:
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  gateway:
    image: stfdigital-plataforma-gateway
    ports:
     - "8765:8765"
     - "47965:47965"
    environment:
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  services:
    image: stfdigital-plataforma-services
    ports:
     - "8081:8081"
     - "8181:8181"
     - "47981:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  mongo:
    ports:
     - "27017:27017"
  documents:
    image: stfdigital-plataforma-documents
    ports:
     - "8094:8094"
     - "8194:8194"
     - "47994:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
     - onlyoffice.documentserver.host=gateway
     - onlyoffice.server.address=https://docker:443
    links:
     - onlyoffice:docker
  peticionamento:
    image: stfdigital-autuacao-peticionamento
    ports:
     - "8090:8090"
     - "8190:8190"
     - "47990:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  recebimento:
    image: stfdigital-autuacao-recebimento
    ports:
     - "8091:8091"
     - "8191:8191"
     - "47991:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  autuacao:
    image: stfdigital-autuacao-autuacao
    ports:
     - "8092:8092"
     - "8192:8192"
     - "47992:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  distribuicao:
    image: stfdigital-autuacao-distribuicao
    ports:
     - "8093:8093"
     - "8193:8193"
     - "47993:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  ui:
    image: stfdigital-plataforma-ui
    ports:
     - "8443:8443"
  userauthentication:
    image: stfdigital-plataforma-userauthentication
    ports:
     - "8095:8095"
     - "8195:8195"
     - "47995:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  onlyoffice:
    image: svendowideit/ambassador
    ports:
     - "443:443"
    environment:
     - ONLYOFFICE_PORT_443_TCP=tcp://10.112.20.123:443