version: '2'
services:
  rabbit:
    container_name: rabbit
    image: rabbitmq:management
    ports:
     - "5672:5672"
     - "15672:15672"
  discovery:
    container_name: discovery
    image: discovery
    ports:
     - "8761:8761"
  gateway:
    container_name: gateway
    image: gateway
    ports:
     - "8765:8765"
  services:
    container_name: services
    image: services
    ports:
     - "8081:8081"
     - "8181:8181"
    environment:
     - spring.profiles.active=development
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,suspend=n
  mongo:
    container_name: mongo
    image: mongo:3
    ports:
     - "27017:27017"
  documents:
    container_name: documents
    image: documents
    command: --onlyoffice.documentserver.host=digital.stf.jus.br --onlyoffice.documentserver.protocol=https
    ports:
     - "8094:8094"
     - "8194:8194"
     - "47994:47994"
    environment:
     - spring.profiles.active=development
     - JAVA_OPTS=-Xdebug, -Xrunjdwp:server=y,transport=dt_socket,address=47994,suspend=n
  peticionamento:
    container_name: peticionamento
    image: peticionamento
    ports:
     - "8090:8090"
     - "8190:8190"
    environment:
     - spring.profiles.active=development
  recebimento:
    container_name: recebimento
    image: recebimento
    ports:
     - "8091:8091"
     - "8191:8191"
    environment:
     - spring.profiles.active=development
  autuacao:
    container_name: autuacao
    image: autuacao
    ports:
     - "8092:8092"
     - "8192:8192"
    environment:
     - spring.profiles.active=development
  distribuicao:
    container_name: distribuicao
    image: distribuicao
    ports:
     - "8093:8093"
     - "8193:8193"
    environment:
     - spring.profiles.active=development
  ui:
    container_name: ui
    image: plataforma-ui
    ports:
     - "8443:8443"