create sequence corporativo.seq_pais increment by 1 start with 1 nomaxvalue minvalue 1 nocycle nocache;
create table corporativo.pais (seq_pais bigint not null, nom_pais varchar2(100) not null, constraint pk_pais primary key (seq_pais));
alter table corporativo.pais add constraint uk_pais_nom_pais unique (nom_pais);

Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ANGOLA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'EMIRADOS ÁRABES UNIDOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ANGUILA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ALBÂNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ARMÊNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ANTILHAS HOLANDESAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ÁUSTRIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ARUBA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'AZERBAIJÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BARBADOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BÉLGICA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BURQUINA FASO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BURUNDI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BERMUDAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BOLÍVIA');

Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BRASIL');
SET @brasil = corporativo.seq_pais.currval;

Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BOTSUANA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BIELORRÚSSIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BELIZE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'COSTA DO MARFIM');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CAMARÕES');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'COLÔMBIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'COSTA RICA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHA DO NATAL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CHIPRE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ALEMANHA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'DJIBOUTI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'REPÚBLICA DOMINICANA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'EQUADOR');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ESTÔNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'EGITO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'FINLÂNDIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'FIJI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS FALKLAND');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'FAROE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'FRANÇA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'FRANÇA METROPOLITANA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GRANADA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GEÓRGIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUIANA FRANCESA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GANA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GROENLÂNDIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GRÉCIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS GEÓRGIA DO SUL E SANDWICH DO SUL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUIANA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHA HEARD E ILHAS MCDONALD');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CROÁCIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'HUNGRIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'IRLANDA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUERNESEY');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ISRAEL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ITÁLIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'QUIRGUISTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'KIRIBATI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'COREIA DO SUL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LIECHTENSTEIN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LIBÉRIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MÔNACO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MADAGASCAR');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MACEDÔNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MAURÍCIO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MALAWI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NOVA CALEDÔNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PAÍSES BAIXOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NIUE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'POLINÉSIA FRANCESA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PAQUISTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CATAR');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS SALOMÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SERRA LEOA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SURINAME');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'EL SALVADOR');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CHADE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TOGO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TUNÍSIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TAIWAN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'UGANDA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÃO VICENTE E GRANADINAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS VIRGENS AMERICANAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'IÊMEN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LÍBIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'REPÚBLICA DEMOCRÁTICA DO CONGO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUINÉ');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BAHREIN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'KUWAIT');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CONGO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SAMOA AMERICANA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'REPÚBLICA CENTRO-AFRICANA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ERITREIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MICRONÉSIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUADALUPE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUAM');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'HONG KONG');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CAZAQUISTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS MARIANAS DO NORTE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PALAU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SANTA HELENA, ASCENSÃO E TRISTÃO DA CUNHA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'WALLIS E FUTUNA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LAOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MACAU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHA NORFOLK');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS TURCAS E CAICOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TURCOMENISTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SAMOA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LUXEMBURGO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'COREIA DO NORTE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ALANDA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CURAÇAU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHA DE MAN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS MENORES AFASTADAS DOS ESTADOS UNIDOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PAÍSES BAIXOS CARIBENHOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PALESTINA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÃO BARTOLOMEU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'COLETIVIDADE DE SÃO MARTINHO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÃO MARTINHO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SUDÃO DO SUL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TIMOR LESTE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ÍNDIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'IRÃ');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ISLÂNDIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'JAMAICA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'JAPÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'QUÊNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CAMBOJA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'COMORES');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÃO CRISTÓVÃO E NEVES');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS CAIMAN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SANTA LÚCIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LESOTO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LITUÂNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MARROCOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MOLDÁVIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS MARSHALL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MYANMAR');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MARTINICA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MAURITÂNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MALDIVAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MÉXICO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NAMÍBIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NÍGER');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NORUEGA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NAURU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NOVA ZELÂNDIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PANAMÁ');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PAPUA-NOVA GUINÉ');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS PITCAIRN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PORTUGAL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PARAGUAI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'REUNIÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ARÁBIA SAUDITA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SEICHELES');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CINGAPURA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ESLOVÊNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ESLOVÁQUIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SOMÁLIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÍRIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TERRAS AUSTRAIS E ANTÁRTICAS FRANCESAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TADJIQUISTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TONGA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TURQUIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TANZÂNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'UCRÂNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ESTADOS UNIDOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'VENEZUELA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS VIRGENS BRITÂNICAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MAIOTE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ÁFRICA DO SUL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ZIMBÁBUE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BUTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'FILIPINAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ANTÁRTIDA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BÓSNIA­HERZEGOVINA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BENIM');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BAHAMAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CANADÁ');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CABO VERDE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'DINAMARCA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GÂMBIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUATEMALA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'HONDURAS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'JERSEY');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MONTSERRAT');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NEPAL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÃO PEDRO E MIQUELÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SVALBARD E JAN MAYEN');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TOQUELAU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'UZBEQUISTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ZÂMBIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MOÇAMBIQUE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SUDÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TUVALU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ROMÊNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÉRVIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MONTENEGRO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ANDORRA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ANTÍGUA E BARBUDA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ARGENTINA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'AUSTRÁLIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BANGLADESH');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BULGÁRIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'BRUNEI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHA BOUVET');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS DOS COCOS');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SUÍÇA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CHILE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CHINA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'CUBA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'REPÚBLICA TCHECA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'DOMINICA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ARGÉLIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ESPANHA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ETIÓPIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GABÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GIBRALTAR');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUINÉ EQUATORIAL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'GUINÉ-BISSAU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'HAITI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'INDONÉSIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'IRAQUE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'JORDÂNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LÍBANO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'LETÔNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MONGÓLIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NIGÉRIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'OMÃ');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PORTO RICO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'RUANDA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SENEGAL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SUAZILÂNDIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TAILÂNDIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'URUGUAI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'VIETNÃ');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SRI LANKA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MALI');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MALTA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'MALÁSIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'NICARÁGUA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'PERU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'POLÔNIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'RÚSSIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SUÉCIA');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SAN MARINO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SÃO TOMÉ E PRÍNCIPE');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'TRINIDAD E TOBAGO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'VATICANO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'VANUATU');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'AFEGANISTÃO');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'ILHAS COOK');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'SAARA OCIDENTAL');
Insert into CORPORATIVO.PAIS (SEQ_PAIS,NOM_PAIS) values (corporativo.seq_pais.nextval,'REINO UNIDO');

create sequence corporativo.seq_unidade_federacao increment by 1 start with 1 nomaxvalue minvalue 1 nocycle nocache;
create table corporativo.unidade_federacao (seq_unidade_federacao bigint not null, nom_unidade_federacao varchar2(100) not null, sig_unidade_federacao varchar2(3) not null, seq_pais bigint not null, constraint pk_unidade_federacao primary key (seq_unidade_federacao));
alter table corporativo.unidade_federacao add constraint uk_unfe_sig_unidade_federacao  unique (sig_unidade_federacao, seq_pais);
alter table corporativo.unidade_federacao add constraint uk_unfe_nom_unidade_federacao  unique (nom_unidade_federacao, seq_pais);
alter table corporativo.unidade_federacao add constraint fk_pais_unfe foreign key (seq_pais) references corporativo.pais(seq_pais);

Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Acre','AC',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Alagoas','AL',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Amazonas','AM',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Amapá','AP',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Bahia','BA',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Ceará','CE',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Distrito Federal','DF',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Espírito Santo','ES',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Goiás','GO',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Maranhão','MA',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Minas Gerais','MG',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Mato Grosso do Sul','MS',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Mato Grosso','MT',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Pará','PA',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Paraíba','PB',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Pernambuco','PE',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Piauí','PI',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Paraná','PR',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Rio de Janeiro','RJ',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Rio Grande do Norte','RN',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Rondônia','RO',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Roraima','RR',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Rio Grande do Sul','RS',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Santa Catarina','SC',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Sergipe','SE',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'São Paulo','SP',@brasil);
Insert into CORPORATIVO.UNIDADE_FEDERACAO (SEQ_UNIDADE_FEDERACAO,NOM_UNIDADE_FEDERACAO,SIG_UNIDADE_FEDERACAO,SEQ_PAIS) values (corporativo.seq_unidade_federacao.nextval,'Tocantins','TO',@brasil);